# Generated by Django 5.0.2 on 2024-04-07 00:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('date', models.DateField(max_length=10)),
                ('email', models.EmailField(max_length=75)),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='People', to='Person.dni')),
            ],
            bases=(models.Model, datetime.date),
        ),
    ]
